### ISSUE TITLE
Add Blender Support - Questions topic

### ISSUE THREAD

**Issue by auguu** [Wizard-collab/Wizard#33]
Hello ! Je fais cette issue pour poster toutes mes questions et problèmes rencontrés pendant que je pipe Blender !

EDIT: je rajoute la road map et l'avancement.

### ROADMAP:
- [x] Shelf Wizard UI
    - [x] Shelf - Load UI in Blender
    - [x] Shelf - `Save File` button
    - [x] Shelf - `Add Export Group` button
    - [x] Shelf - `Add Export Set` button
    - [x] Shelf - `Import References` button    |    Import publish (`.abc`)
    - [x] Shelf - `Publish File` button    |    Publish from Blender (`.abc`) - **ONLY TESTED FOR MODELING**
    - [x] Shelf - `Refresh References` button
    - [x] Shelf - `Set Frame Range` button
    - [x] Shelf - `Set Frame Range with Preroll and Postroll` button
    - [x] Shelf - `Set Render Settings` button
- [ ] Animation
    - [ ] Import animation publish (`.abc`) - dynamic link through modifier
    - [ ] Playblast animation (`Blender command line`)
    - [ ] Publish animation (`.abc`)

**Comment by Wizard-collab** [comment]
Je ferme le topic pour le moment - A réouvrir si problème
