### ISSUE TITLE
Houdini - Topic

### ISSUE THREAD

**Issue by Wizard-collab** [Wizard-collab/Wizard#39]
The topic for the integration of Houdini

### ROADMAP:
- [x] Shelf Wizard UI
    - [x] Shelf - Load UI in Houdini
    - [x] Shelf - `Save File` button
    - [x] Shelf - `Import References` button
        - [x] Import geometry (`.abc`)
        - [x] Import camera (`.abc`)
    - [x] Shelf - `Publish File` button
        - [x] Publish scene (`.hip`)
        - [x] Publish geometry (`.abc`) 
        - [x] Publish vdb (`.vdb`)
        - [x] Guerilla tags
    - [x] Shelf - `Refresh References` button
    - [x] Shelf - `Set Frame Range` button
- [x] Animation
    - [x] Flipbook

**Comment by Wizard-collab** [comment]
Je ferme le topic pour le moment - A réouvrir si probleme
